import os from "os"

// console.info(os.platform())
// console.table(os.cpus())

// console.info(os.EOL)
// console.info(os.arch())
// console.info(os.constants)
// console.info(os.cpus())
// console.info(os.devNull)
// console.info(os.endianness())
// console.info(os.freemem())
// // console.info(os.getPriority([pid]))
// console.info(os.homedir())
// console.info(os.hostname())
// console.info(os.loadavg())
// console.info(os.networkInterfaces())
// console.info(os.platform())
// console.info(os.release())
// // console.info(os.setPriority())
// console.info(os.tmpdir())
// console.info(os.totalmem())
// console.info(os.type())
// console.info(os.uptime())
console.info(os.userInfo())